// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ArchingController from "./arching_controller"
application.register("arching", ArchingController)

import CustomersController from "./customers_controller"
application.register("customers", CustomersController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import ItemController from "./item_controller"
application.register("item", ItemController)

import MarketController from "./market_controller"
application.register("market", MarketController)

import MenuController from "./menu_controller"
application.register("menu", MenuController)

import OrdersController from "./orders_controller"
application.register("orders", OrdersController)

import PendingController from "./pending_controller"
application.register("pending", PendingController)

import ProductsController from "./products_controller"
application.register("products", ProductsController)

import PurchaseController from "./purchase_controller"
application.register("purchase", PurchaseController)

import SalesController from "./sales_controller"
application.register("sales", SalesController)

import SearchController from "./search_controller"
application.register("search", SearchController)

import TransaktionsController from "./transaktions_controller"
application.register("transaktions", TransaktionsController)

import TransferController from "./transfer_controller"
application.register("transfer", TransferController)

import UsersController from "./users_controller"
application.register("users", UsersController)

import WarehousesController from "./warehouses_controller"
application.register("warehouses", WarehousesController)
